# Site settings
title: iest.co
email: hello@iest.co
description: >
  <strong>Iestyn Williams</strong> is an engineer and designer, living and
  working in Foggy London Town.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://iest.co" # the base hostname & protocol for your site
twitter_username: _iest
github_username:  iest

# Build settings
exclude: ['gulpfile.js', 'node_modules', 'package.json', '*.sketch']
markdown: kramdown
kramdown:
  input: GFM

# Code highlighting
highlighting: pygments

# Stylus processor
stylus:
  compress: true
  path: css/main.styl