# Site settings
title: iest.co
email: hello@iest.co
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://iest.co" # the base hostname & protocol for your site
twitter_username: _iest
github_username:  iest

# Build settings
markdown: kramdown
kramdown:
  input: GFM

# Code highlighting
highlighting: pygments