# Site settings
title: iest.co
email: hello_iest@me.com
description: >
  <strong>Iestyn Williams</strong> is an engineer, designer, and coffee snob living and working in London.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://iest.co" # the base hostname & protocol for your site
twitter_username: _iest
github_username:  iest

# Pagination
paginate: 5
paginate_path: "/page:num"

# Build settings
exclude: ['gulpfile.js', 'node_modules', 'package.json', '*.sketch', '*.sublime*']
markdown: kramdown
kramdown:
  input: GFM
  coderay_css: class

# Code highlighting
highlighting: pygments


# Stylus processor
stylus:
  compress: true
  path: css/main.styl

gems: [jekyll-paginate]
